apps:
  bot:
    token: "..."
    prefix: "!"
    # http: # optional, if you want to enable the http server
    #   port: 8080
    #   path: "/" # optional, if you want to configure the HTTP API Base Path
    # ws: # optional, if you want to enable the ws server
    #   port: 8080
    #   path: "/ws" # optional, if you want to configure the WebSocket Path
  # youtubeApi: # if you want to start http server for youtube api, used by official web client
  #   port: 8082
lavalink: # optional, if you want to use lavalink instead of built in player
  host: "0.0.0.0"
  port: 2333
  password: "youshallnotpass"
# spotify: # optional, if you want to enable spotify support
#   clientId: "..."
#   clientSecret: "..."
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  database: "degabut"
# youtube: # optional config for youtube module
#   oauth: # if you want to use oauth for youtube, used on youtube api and youtube module
#     refreshToken: "1//..."
#   proxy: # if you want to proxy http request to youtube
#     protocol: "http" # "http" or "https"
#     host: "host"
#     port: 80
#     username: "..."
#     password: "..."
# auth: # optional
#   jwt: # must be enabled if running bot http server / youtube api server
#     secret: "..."
#   discordOAuth: # must be enabled if running bot http server
#     clientId: "..."
#     clientSecret: "..."
logging:
  level: "log"
  # printConfig: true # optional, for debugging purpose, print out config when application is started
